# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QTreeView, QFileSystemModel, QVBoxLayout, QPushButton, QWidget, QFileDialog
import pandas
import numpy
import matplotlib.pyplot as plt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(625, 550)
        Form.setMinimumSize(QtCore.QSize(625, 550))
        Form.setMaximumSize(QtCore.QSize(625, 550))
        Form.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.xMinPushButton = QtWidgets.QPushButton(Form)
        self.xMinPushButton.setGeometry(QtCore.QRect(110, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.xMinPushButton.setFont(font)
        self.xMinPushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.xMinPushButton.setObjectName("xMinPushButton")
        self.xminLineEdit = QtWidgets.QLineEdit(Form)
        self.xminLineEdit.setGeometry(QtCore.QRect(330, 70, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.xminLineEdit.setFont(font)
        self.xminLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.xminLineEdit.setObjectName("xminLineEdit")
        self.xmaxLineEdit = QtWidgets.QLineEdit(Form)
        self.xmaxLineEdit.setGeometry(QtCore.QRect(330, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.xmaxLineEdit.setFont(font)
        self.xmaxLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.xmaxLineEdit.setObjectName("xmaxLineEdit")
        self.browserPushButton = QtWidgets.QPushButton(Form)
        self.browserPushButton.setGeometry(QtCore.QRect(450, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.browserPushButton.setFont(font)
        self.browserPushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.browserPushButton.setObjectName("browserPushButton")
        self.xLineInterval = QtWidgets.QLineEdit(Form)
        self.xLineInterval.setGeometry(QtCore.QRect(330, 270, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.xLineInterval.setFont(font)
        self.xLineInterval.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.xLineInterval.setObjectName("xLineInterval")
        self.yLineInterval = QtWidgets.QLineEdit(Form)
        self.yLineInterval.setGeometry(QtCore.QRect(330, 320, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.yLineInterval.setFont(font)
        self.yLineInterval.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.yLineInterval.setObjectName("yLineInterval")
        self.xLineEdit = QtWidgets.QLineEdit(Form)
        self.xLineEdit.setGeometry(QtCore.QRect(330, 370, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.xLineEdit.setFont(font)
        self.xLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.xLineEdit.setObjectName("xLineEdit")
        self.yLabel = QtWidgets.QLineEdit(Form)
        self.yLabel.setGeometry(QtCore.QRect(330, 420, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.yLabel.setFont(font)
        self.yLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.yLabel.setObjectName("yLabel")
        self.browserLineEdit = QtWidgets.QLineEdit(Form)
        self.browserLineEdit.setGeometry(QtCore.QRect(30, 10, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.browserLineEdit.setFont(font)
        self.browserLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10\n"
"")
        self.browserLineEdit.setObjectName("browserLineEdit")
        self.plotPushButton = QtWidgets.QPushButton(Form)
        self.plotPushButton.setGeometry(QtCore.QRect(210, 480, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.plotPushButton.setFont(font)
        self.plotPushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.plotPushButton.setObjectName("plotPushButton")
        self.xMaxPushButton = QtWidgets.QPushButton(Form)
        self.xMaxPushButton.setGeometry(QtCore.QRect(110, 120, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.xMaxPushButton.setFont(font)
        self.xMaxPushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.xMaxPushButton.setObjectName("xMaxPushButton")
        self.xIntervalPushButton = QtWidgets.QPushButton(Form)
        self.xIntervalPushButton.setGeometry(QtCore.QRect(110, 270, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.xIntervalPushButton.setFont(font)
        self.xIntervalPushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.xIntervalPushButton.setObjectName("xIntervalPushButton")
        self.yIntervalPushButton = QtWidgets.QPushButton(Form)
        self.yIntervalPushButton.setGeometry(QtCore.QRect(110, 320, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.yIntervalPushButton.setFont(font)
        self.yIntervalPushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.yIntervalPushButton.setObjectName("yIntervalPushButton")
        self.xLabelPushButton = QtWidgets.QPushButton(Form)
        self.xLabelPushButton.setGeometry(QtCore.QRect(110, 370, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.xLabelPushButton.setFont(font)
        self.xLabelPushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.xLabelPushButton.setObjectName("xLabelPushButton")
        self.yLabelPushButton = QtWidgets.QPushButton(Form)
        self.yLabelPushButton.setGeometry(QtCore.QRect(110, 420, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.yLabelPushButton.setFont(font)
        self.yLabelPushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.yLabelPushButton.setObjectName("yLabelPushButton")
        self.title = QtWidgets.QLineEdit(Form)
        self.title.setGeometry(QtCore.QRect(470, 500, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(6)
        self.title.setFont(font)
        self.title.setAutoFillBackground(True)
        self.title.setStyleSheet("border-radius:10;\n"
"background-color: rgb(0, 0, 255);")
        self.title.setObjectName("title")
        self.YminLineEdit = QtWidgets.QLineEdit(Form)
        self.YminLineEdit.setGeometry(QtCore.QRect(330, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.YminLineEdit.setFont(font)
        self.YminLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.YminLineEdit.setObjectName("YminLineEdit")
        self.yMaxPushButton = QtWidgets.QPushButton(Form)
        self.yMaxPushButton.setGeometry(QtCore.QRect(110, 220, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.yMaxPushButton.setFont(font)
        self.yMaxPushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.yMaxPushButton.setObjectName("yMaxPushButton")
        self.YmaxLineEdit = QtWidgets.QLineEdit(Form)
        self.YmaxLineEdit.setGeometry(QtCore.QRect(330, 220, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.YmaxLineEdit.setFont(font)
        self.YmaxLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.YmaxLineEdit.setObjectName("YmaxLineEdit")
        self.yminPushButton = QtWidgets.QPushButton(Form)
        self.yminPushButton.setGeometry(QtCore.QRect(110, 170, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.yminPushButton.setFont(font)
        self.yminPushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10;")
        self.yminPushButton.setObjectName("yminPushButton")
        
        self.browserPushButton.clicked.connect(self.browseFolder)
        self.plotPushButton.clicked.connect(self.plot)
        
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MEOS Isıl Tasarım Ekibi Plotv01"))
        self.xMinPushButton.setText(_translate("Form", "Xmin"))
        self.browserPushButton.setText(_translate("Form", "Gözat..."))
        self.plotPushButton.setText(_translate("Form", "Plot"))
        self.xMaxPushButton.setText(_translate("Form", "Xmax"))
        self.xIntervalPushButton.setText(_translate("Form", "Xinterval"))
        self.yIntervalPushButton.setText(_translate("Form", "Yinterval"))
        self.xLabelPushButton.setText(_translate("Form", "X"))
        self.yLabelPushButton.setText(_translate("Form", "Y"))
        self.title.setText(_translate("Form", "   MEOS ISIL TASARIM EKİBİ"))
        self.yMaxPushButton.setText(_translate("Form", "Ymax"))
        self.yminPushButton.setText(_translate("Form", "Ymin"))

    def browseFolder(self):
        self.text, self.placeholder        = QFileDialog.getOpenFileName(None, 'Select file')
        fileName                           = self.browserLineEdit.setText(self.text)
        
        
    def plot(self):
        
        self.xMinimum                      = float((self.xminLineEdit.text()))
        self.xMaximum                      = float((self.xmaxLineEdit.text()))
        self.yMinimum                      = float((self.YminLineEdit.text()))
        self.yMaximum                      = float((self.YmaxLineEdit.text()))
        self.xInterval                     = float((self.xLineInterval.text()))
        self.yInterval                     = float((self.yLineInterval.text()))
        self.xAxis                         = self.xLineEdit.text()
        self.yAxis                         = self.yLabel.text()
        
        data                               = pandas.read_csv("data.txt",sep="\t")
        xDataInterval                      = numpy.linspace(self.xMinimum, self.xMaximum, int(self.xInterval))
        yDataInterval                      = numpy.linspace(self.yMinimum, self.yMaximum, int(self.yInterval))
        
        headerList                         = data.columns.tolist()
        headerListSecond                   = headerList[1:]
        
        plt.grid(True, color='gray', linestyle='--', linewidth=0.5)
        data.plot(headerList[0],headerListSecond)
        plt.xticks(xDataInterval)
        plt.yticks(yDataInterval)
        plt.show()
        

        
        
        

        
        
        
        

    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
